package com.shopbook.home.model.am;

import com.shopbook.home.model.am.common.ShBkHomeAm;
import com.shopbook.home.model.view.HmSkuVImpl;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 08 07:01:36 EET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShBkHomeAmImpl extends ApplicationModuleImpl implements ShBkHomeAm {
    /**
     * This is the default constructor (do not remove).
     */
    public ShBkHomeAmImpl() {
    }
    // This method get all the childs of the parent cat given to it
    public void getAllChildCats(String vPrntCat)  {
        DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
        CallableStatement statement = (CallableStatement)dbti.createCallableStatement(("call get_cat_tree(?);"), 0);
        try {
            statement.setString(1, vPrntCat);
            statement.execute();
        }catch (SQLException sqlerr) {
                throw new JboException(sqlerr);
            } finally {
                try {
                    if (statement != null) {
                        statement.close();
                    }
                } catch (SQLException closeerr) {
                    throw new JboException(closeerr);
                }
            }
 
    }
    // This method for adding sku to my bag
    public void addToMyBag(String pUserId, String pSkuClrCode,String pSizeCode, 
                           String pUnitCode, BigDecimal pQty, BigDecimal pUnitPrice) {
            DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
            CallableStatement statement = (CallableStatement)dbti.createCallableStatement(("call add_to_bag(?,?,?,?,?,?);"), 0);
            try {
                System.out.println("1- "+pUserId +
                "2- "+pSkuClrCode +
                "3- "+pSizeCode +
                "4- "+pUnitCode +
                "5- "+pQty +
                "6- "+pUnitPrice);
                statement.setString(1, pUserId);
                statement.setString(2,pSkuClrCode);
                statement.setString(3,pSizeCode);
                statement.setString(4,pUnitCode);
                statement.setBigDecimal(5,pQty);
                statement.setBigDecimal(6,pUnitPrice);
                statement.execute();
    //            System.out.println("Done.");
     //           System.out.println(statement.toString());
            } catch (SQLException sqlerr) {
                throw new JboException(sqlerr);
            } finally {
                try {
                    if (statement != null) {
                        statement.close();
                    }
                } catch (SQLException closeerr) {
                    throw new JboException(closeerr);
                }
            }
        }    
    /**
     * Container's getter for SysParametersV.
     * @return SysParametersV
     */
    public ViewObjectImpl getSysParametersV() {
        return (ViewObjectImpl) findViewObject("SysParametersV");
    }

    /**
     * Container's getter for HmShopSubCatsV.
     * @return HmShopSubCatsV
     */
    public ViewObjectImpl getHmShopSubCatsV() {
        return (ViewObjectImpl) findViewObject("HmShopSubCatsV");
    }

    /**
     * Container's getter for HmSkusVold.
     * @return HmSkusVold
     */
    public ViewObjectImpl getHmSkusVold() {
        return (ViewObjectImpl) findViewObject("HmSkusVold");
    }

    /**
     * Container's getter for ShopsV.
     * @return ShopsV
     */
    public ViewObjectImpl getShopsV() {
        return (ViewObjectImpl) findViewObject("ShopsV");
    }

    /**
     * Container's getter for DetSkusV.
     * @return DetSkusV
     */
    public ViewObjectImpl getDetSkusV() {
        return (ViewObjectImpl) findViewObject("DetSkusV");
    }

    /**
     * Container's getter for DetSkuColorsV.
     * @return DetSkuColorsV
     */
    public ViewObjectImpl getDetSkuColorsV() {
        return (ViewObjectImpl) findViewObject("DetSkuColorsV");
    }

    /**
     * Container's getter for DetSkuSizeColorsV.
     * @return DetSkuSizeColorsV
     */
    public ViewObjectImpl getDetSkuSizeColorsV() {
        return (ViewObjectImpl) findViewObject("DetSkuSizeColorsV");
    }

    /**
     * Container's getter for DetSkuClrImagesV.
     * @return DetSkuClrImagesV
     */
    public ViewObjectImpl getDetSkuClrImagesV() {
        return (ViewObjectImpl) findViewObject("DetSkuClrImagesV");
    }

    /**
     * Container's getter for BrandsV.
     * @return BrandsV
     */
    public ViewObjectImpl getBrandsV() {
        return (ViewObjectImpl) findViewObject("BrandsV");
    }

    /**
     * Container's getter for ManufacturesV.
     * @return ManufacturesV
     */
    public ViewObjectImpl getManufacturesV() {
        return (ViewObjectImpl) findViewObject("ManufacturesV");
    }

    /**
     * Container's getter for ModelsV.
     * @return ModelsV
     */
    public ViewObjectImpl getModelsV() {
        return (ViewObjectImpl) findViewObject("ModelsV");
    }

    /**
     * Container's getter for DetSkuUnitsV.
     * @return DetSkuUnitsV
     */
    public ViewObjectImpl getDetSkuUnitsV() {
        return (ViewObjectImpl) findViewObject("DetSkuUnitsV");
    }

    /**
     * Container's getter for DetSkuPropDetsV.
     * @return DetSkuPropDetsV
     */
    public ViewObjectImpl getDetSkuPropDetsV() {
        return (ViewObjectImpl) findViewObject("DetSkuPropDetsV");
    }

    /**
     * Container's getter for SkuAssemblyCompsV.
     * @return SkuAssemblyCompsV
     */
    public ViewObjectImpl getSkuAssemblyCompsV() {
        return (ViewObjectImpl) findViewObject("SkuAssemblyCompsV");
    }

    /**
     * Container's getter for SkuCompAssembliesV.
     * @return SkuCompAssembliesV
     */
    public ViewObjectImpl getSkuCompAssembliesV() {
        return (ViewObjectImpl) findViewObject("SkuCompAssembliesV");
    }

    /**
     * Container's getter for VerifyPswdV.
     * @return VerifyPswdV
     */
    public ViewObjectImpl getVerifyPswdV() {
        return (ViewObjectImpl) findViewObject("VerifyPswdV");
    }

    /**
     * Container's getter for UserSignupV.
     * @return UserSignupV
     */
    public ViewObjectImpl getUserSignupV() {
        return (ViewObjectImpl) findViewObject("UserSignupV");
    }

    /**
     * Container's getter for ResetPswrdReqV.
     * @return ResetPswrdReqV
     */
    public ViewObjectImpl getResetPswrdReqV() {
        return (ViewObjectImpl) findViewObject("ResetPswrdReqV");
    }

    /**
     * Container's getter for SkuPostsV.
     * @return SkuPostsV
     */
    public ViewObjectImpl getSkuPostsV() {
        return (ViewObjectImpl) findViewObject("SkuPostsV");
    }

    /**
     * Container's getter for ShoppingMasterV.
     * @return ShoppingMasterV
     */
    public ViewObjectImpl getShoppingMasterV() {
        return (ViewObjectImpl) findViewObject("ShoppingMasterV");
    }

    /**
     * Container's getter for ShoppingDetV.
     * @return ShoppingDetV
     */
    public ViewObjectImpl getShoppingDetV() {
        return (ViewObjectImpl) findViewObject("ShoppingDetV");
    }

    /**
     * Container's getter for HmSkuSzClrVold.
     * @return HmSkuSzClrVold
     */
    public ViewObjectImpl getHmSkuSzClrVold() {
        return (ViewObjectImpl) findViewObject("HmSkuSzClrVold");
    }

    /**
     * Container's getter for GeneralTermsV.
     * @return GeneralTermsV
     */
    public ViewObjectImpl getGeneralTermsV() {
        return (ViewObjectImpl) findViewObject("GeneralTermsV");
    }

    /**
     * Container's getter for ReturnTermsV.
     * @return ReturnTermsV
     */
    public ViewObjectImpl getReturnTermsV() {
        return (ViewObjectImpl) findViewObject("ReturnTermsV");
    }

    /**
     * Container's getter for ShippingTermsV.
     * @return ShippingTermsV
     */
    public ViewObjectImpl getShippingTermsV() {
        return (ViewObjectImpl) findViewObject("ShippingTermsV");
    }

    /**
     * Container's getter for LangCurrV.
     * @return LangCurrV
     */
    public ViewObjectImpl getLangCurrV() {
        return (ViewObjectImpl) findViewObject("LangCurrV");
    }

    /**
     * Container's getter for UserPermissionsV.
     * @return UserPermissionsV
     */
    public ViewObjectImpl getUserPermissionsV() {
        return (ViewObjectImpl) findViewObject("UserPermissionsV");
    }

    /**
     * Container's getter for UsersProfileV.
     * @return UsersProfileV
     */
    public ViewObjectImpl getUsersProfileV() {
        return (ViewObjectImpl) findViewObject("UsersProfileV");
    }

    /**
     * Container's getter for ShopImagesV1.
     * @return ShopImagesV1
     */
    public ViewObjectImpl getShopImagesV1() {
        return (ViewObjectImpl) findViewObject("ShopImagesV1");
    }

    /**
     * Container's getter for SysIamgesView.
     * @return SysIamgesView
     */
    public ViewObjectImpl getSysIamgesView() {
        return (ViewObjectImpl) findViewObject("SysIamgesView");
    }

    /**
     * Container's getter for SliderImagesV.
     * @return SliderImagesV
     */
    public ViewObjectImpl getSliderImagesV() {
        return (ViewObjectImpl) findViewObject("SliderImagesV");
    }

    /**
     * Container's getter for HmSkuColorsV.
     * @return HmSkuColorsV
     */
    public ViewObjectImpl getHmSkuColorsV() {
        return (ViewObjectImpl) findViewObject("HmSkuColorsV");
    }

    /**
     * Container's getter for HmSkuV1.
     * @return HmSkuV1
     */
    public HmSkuVImpl getHmSkuV1() {
        return (HmSkuVImpl) findViewObject("HmSkuV1");
    }

    /**
     * Container's getter for HmSkuColorsV1.
     * @return HmSkuColorsV1
     */
    public ViewObjectImpl getHmSkuColorsV1() {
        return (ViewObjectImpl) findViewObject("HmSkuColorsV1");
    }

    /**
     * Container's getter for YearsV.
     * @return YearsV
     */
    public ViewObjectImpl getYearsV() {
        return (ViewObjectImpl) findViewObject("YearsV");
    }

    /**
     * Container's getter for SkuFilterColorsV.
     * @return SkuFilterColorsV
     */
    public ViewObjectImpl getSkuFilterColorsV() {
        return (ViewObjectImpl) findViewObject("SkuFilterColorsV");
    }

    /**
     * Container's getter for SkuFilterSizesV.
     * @return SkuFilterSizesV
     */
    public ViewObjectImpl getSkuFilterSizesV() {
        return (ViewObjectImpl) findViewObject("SkuFilterSizesV");
    }


    /**
     * Container's getter for CitiesLovV.
     * @return CitiesLovV
     */
    public ViewObjectImpl getCitiesLovV() {
        return (ViewObjectImpl) findViewObject("CitiesLovV");
    }


    /**
     * Container's getter for ShopcatSkuVL1.
     * @return ShopcatSkuVL1
     */
    public ViewLinkImpl getShopcatSkuVL1() {
        return (ViewLinkImpl) findViewLink("ShopcatSkuVL1");
    }

    /**
     * Container's getter for SkuToColorsVL1.
     * @return SkuToColorsVL1
     */
    public ViewLinkImpl getSkuToColorsVL1() {
        return (ViewLinkImpl) findViewLink("SkuToColorsVL1");
    }

    /**
     * Container's getter for SkuClrToSkuSzClrVL1.
     * @return SkuClrToSkuSzClrVL1
     */
    public ViewLinkImpl getSkuClrToSkuSzClrVL1() {
        return (ViewLinkImpl) findViewLink("SkuClrToSkuSzClrVL1");
    }

    /**
     * Container's getter for SkuClrToSkuClrImgVL1.
     * @return SkuClrToSkuClrImgVL1
     */
    public ViewLinkImpl getSkuClrToSkuClrImgVL1() {
        return (ViewLinkImpl) findViewLink("SkuClrToSkuClrImgVL1");
    }

    /**
     * Container's getter for SkuToSkuUnitVL1.
     * @return SkuToSkuUnitVL1
     */
    public ViewLinkImpl getSkuToSkuUnitVL1() {
        return (ViewLinkImpl) findViewLink("SkuToSkuUnitVL1");
    }

    /**
     * Container's getter for SkuToSkuPropVL1.
     * @return SkuToSkuPropVL1
     */
    public ViewLinkImpl getSkuToSkuPropVL1() {
        return (ViewLinkImpl) findViewLink("SkuToSkuPropVL1");
    }

    /**
     * Container's getter for MainSkuToAssemblyVL1.
     * @return MainSkuToAssemblyVL1
     */
    public ViewLinkImpl getMainSkuToAssemblyVL1() {
        return (ViewLinkImpl) findViewLink("MainSkuToAssemblyVL1");
    }

    /**
     * Container's getter for SkuToAssCompVL1.
     * @return SkuToAssCompVL1
     */
    public ViewLinkImpl getSkuToAssCompVL1() {
        return (ViewLinkImpl) findViewLink("SkuToAssCompVL1");
    }

    /**
     * Container's getter for SkuPostVL1.
     * @return SkuPostVL1
     */
    public ViewLinkImpl getSkuPostVL1() {
        return (ViewLinkImpl) findViewLink("SkuPostVL1");
    }

    /**
     * Container's getter for ShoppingMastDetFK1.
     * @return ShoppingMastDetFK1
     */
    public ViewLinkImpl getShoppingMastDetFK1() {
        return (ViewLinkImpl) findViewLink("ShoppingMastDetFK1");
    }

    /**
     * Container's getter for SkuDetPskuClrToSzVL1.
     * @return SkuDetPskuClrToSzVL1
     */
    public ViewLinkImpl getSkuDetPskuClrToSzVL1() {
        return (ViewLinkImpl) findViewLink("SkuDetPskuClrToSzVL1");
    }

    /**
     * Container's getter for HmSkuVToSkuColorsVL1.
     * @return HmSkuVToSkuColorsVL1
     */
    public ViewLinkImpl getHmSkuVToSkuColorsVL1() {
        return (ViewLinkImpl) findViewLink("HmSkuVToSkuColorsVL1");
    }


    /**
     * Container's getter for ServingOrderMastV1.
     * @return ServingOrderMastV1
     */
    public ViewObjectImpl getServingOrderMastV1() {
        return (ViewObjectImpl) findViewObject("ServingOrderMastV1");
    }

    /**
     * Container's getter for ShoppingDetV1.
     * @return ShoppingDetV1
     */
    public ViewObjectImpl getServingOrderDetsV1() {
        return (ViewObjectImpl) findViewObject("ServingOrderDetsV1");
    }

    /**
     * Container's getter for ServingOrdersMastToDetVL1.
     * @return ServingOrdersMastToDetVL1
     */
    public ViewLinkImpl getServingOrdersMastToDetVL1() {
        return (ViewLinkImpl) findViewLink("ServingOrdersMastToDetVL1");
    }

    /**
     * Container's getter for ShpBagStatusV1.
     * @return ShpBagStatusV1
     */
    public ViewObjectImpl getShpBagStatusV1() {
        return (ViewObjectImpl) findViewObject("ShpBagStatusV1");
    }

    /**
     * Container's getter for newHmSkuV1.
     * @return newHmSkuV1
     */
    public ViewObjectImpl getnewHmSkuV() {
        return (ViewObjectImpl) findViewObject("newHmSkuV");
    }

    /**
     * Container's getter for IndexParentCategories1.
     * @return IndexParentCategories1
     */
    public ViewObjectImpl getIndexHomeCategoriesV() {
        return (ViewObjectImpl) findViewObject("IndexHomeCategoriesV");
    }


    /**
     * Container's getter for IndexChildCategories2.
     * @return IndexChildCategories2
     */
    public ViewObjectImpl getIndexChildCategories1() {
        return (ViewObjectImpl) findViewObject("IndexChildCategories1");
    }

    /**
     * Container's getter for IndexChildCategories1.
     * @return IndexChildCategories1
     */
    public ViewObjectImpl getIndexChildCategories2() {
        return (ViewObjectImpl) findViewObject("IndexChildCategories2");
    }

    /**
     * Container's getter for IndexChildCategoryTreeVL1.
     * @return IndexChildCategoryTreeVL1
     */
    public ViewLinkImpl getIndexChildCategoryTreeVL1() {
        return (ViewLinkImpl) findViewLink("IndexChildCategoryTreeVL1");
    }

    /**
     * Container's getter for ReferencesNamesV1.
     * @return ReferencesNamesV1
     */
    public ViewObjectImpl getReferencesNamesV() {
        return (ViewObjectImpl) findViewObject("ReferencesNamesV");
    }

    /**
     * Container's getter for LangToRefNamevVL1.
     * @return LangToRefNamevVL1
     */
    public ViewLinkImpl getLangToRefNamevVL1() {
        return (ViewLinkImpl) findViewLink("LangToRefNamevVL1");
    }
}

