package com.shopbook.home.model.am.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 08 07:02:09 EET 2022
// ---------------------------------------------------------------------
public interface ShBkHomeAm extends ApplicationModule {
    void addToMyBag(String pUserId, String pSkuClrCode, String pSizeCode, String pUnitCode, BigDecimal pQty,
                    BigDecimal pUnitPrice);
}

