INSERT INTO COUNTRIES (CNTRY_CODE2,CNTRY_NAME,DIAL_CODE,CURR_NAME, CURR_SYMBOL,CURR_CODE,CNTRY_CODE3)
  VALUES
('AD', 'Andorra', 376, 'Euro', '€', 'EUR', 'AND'),
('AE', 'United Arab Emirates', 971, 'United Arab Emirates', 'د.إ', 'AED', 'ARE'),
('AF', 'Afghanistan', 93, 'Afghan afghani', '؋', 'AFN', 'AFG'),
('AG', 'Antigua And Barbuda', 1268, 'East Caribbean dolla', '$', 'XCD', 'ATG'),
('AI', 'Anguilla', 1264, 'East Caribbean dolla', '$', 'XCD', 'AIA'),
('AL', 'Albania', 355, 'Albanian lek', 'L', 'ALL', 'ALB'),
('AM', 'Armenia', 374, 'Armenian dram', '', 'AMD', 'ARM'),
('AN', 'Netherlands Antilles', 599, '', '', ''),
('AO', 'Angola', 244, 'Angolan kwanza', 'Kz', 'AOA', 'AGO'),
('AQ', 'Antarctica', 0, '', '', '', 'ATA'),
('AR', 'Argentina', 54, 'Argentine peso', '$', 'ARS', 'ARG'),
('AS', 'American Samoa', 1684, '', '', '', 'ASM'),
('AT', 'Austria', 43, 'Euro', '€', 'EUR', 'AUT'),
('AU', 'Australia', 61, 'Australian dollar', '$', 'AUD', 'AUS'),
('AW', 'Aruba', 297, 'Aruban florin', 'ƒ', 'AWG', 'ABW'),
('AZ', 'Azerbaijan', 994, 'Azerbaijani manat', '', 'AZN', 'AZE'),
('BA', 'Bosnia and Herzegovina', 387, 'Bosnia and Herzegovi', 'KM or КМ', 'BAM', 'BIH'),
('BB', 'Barbados', 1246, 'Barbadian dollar', '$', 'BBD', 'BRB'),
('BD', 'Bangladesh', 880, 'Bangladeshi taka', '৳', 'BDT', 'BGD'),
('BE', 'Belgium', 32, 'Euro', '€', 'EUR', 'BEL'),
('BF', 'Burkina Faso', 226, 'West African CFA fra', 'Fr', 'XOF', 'BFA'),
('BG', 'Bulgaria', 359, 'Bulgarian lev', 'лв', 'BGN', 'BGR'),
('BH', 'Bahrain', 973, 'Bahraini dinar', '.د.ب', 'BHD', 'BHR'),
('BI', 'Burundi', 257, 'Burundian franc', 'Fr', 'BIF', 'BDI'),
('BJ', 'Benin', 229, 'West African CFA fra', 'Fr', 'XOF', 'BEN'),
('BM', 'Bermuda', 1441, 'Bermudian dollar', '$', 'BMD', 'BMU'),
('BN', 'Brunei', 673, 'Brunei dollar', '$', 'BND', 'BRN'),
('BO', 'Bolivia', 591, 'Bolivian boliviano', 'Bs.', 'BOB', 'BOL'),
('BR', 'Brazil', 55, 'Brazilian real', 'R$', 'BRL', 'BRA'),
('BS', 'Bahamas The', 1242, '', '', '', 'BHS'),
('BT', 'Bhutan', 975, 'Bhutanese ngultrum', 'Nu.', 'BTN', 'BTN'),
('BV', 'Bouvet Island', 0, '', '', '', 'BVT'),
('BW', 'Botswana', 267, 'Botswana pula', 'P', 'BWP', 'BWA'),
('BY', 'Belarus', 375, 'Belarusian ruble', 'Br', 'BYR', 'BLR'),
('BZ', 'Belize', 501, 'Belize dollar', '$', 'BZD', 'BLZ'),
('CA', 'Canada', 1, 'Canadian dollar', '$', 'CAD', 'CAN'),
('CC', 'Cocos (Keeling) Islands', 672, 'Australian dollar', '$', 'AUD', 'CCK'),
('CD', 'Congo The Democratic Republic Of The', 242, '', '', '', 'COD'),
('CF', 'Central African Republic', 236, 'Central African CFA ', 'Fr', 'XAF', 'CAF'),
('CG', 'Congo', 242, '', '', '', 'COG'),
('CH', 'Switzerland', 41, 'Swiss franc', 'Fr', 'CHF', 'CHE'),
('CI', 'Cote D''Ivoire (Ivory Coast)', 225, '', '', '', 'CIV'),
('CK', 'Cook Islands', 682, 'New Zealand dollar', '$', 'NZD', 'COK'),
('CL', 'Chile', 56, 'Chilean peso', '$', 'CLP', 'CHL'),
('CM', 'Cameroon', 237, 'Central African CFA ', 'Fr', 'XAF', 'CMR'),
('CN', 'China', 86, 'Chinese yuan', '¥ or 元', 'CNY', 'CHN'),
('CO', 'Colombia', 57, 'Colombian peso', '$', 'COP', 'COL'),
('CR', 'Costa Rica', 506, 'Costa Rican colón', '₡', 'CRC', 'CRI'),
('CU', 'Cuba', 53, 'Cuban convertible pe', '$', 'CUC', 'CUB'),
('CV', 'Cape Verde', 238, 'Cape Verdean escudo', 'Esc or $', 'CVE', 'CPV'),
('CX', 'Christmas Island', 61, '', '', '', 'CXR'),
('CY', 'Cyprus', 357, 'Euro', '€', 'EUR', 'CYP'),
('CZ', 'Czech Republic', 420, 'Czech koruna', 'Kč', 'CZK', 'CZE'),
('DE', 'Germany', 49, 'Euro', '€', 'EUR', 'DEU'),
('DJ', 'Djibouti', 253, 'Djiboutian franc', 'Fr', 'DJF', 'DJI'),
('DK', 'Denmark', 45, 'Danish krone', 'kr', 'DKK', 'DNK'),
('DM', 'Dominica', 1767, 'East Caribbean dolla', '$', 'XCD', 'DMA'),
('DO', 'Dominican Republic', 1809, 'Dominican peso', '$', 'DOP', 'DOM'),
('DZ', 'Algeria', 213, 'Algerian dinar', 'د.ج', 'DZD', 'DZA'),
('EC', 'Ecuador', 593, 'United States dollar', '$', 'USD', 'ECU'),
('EE', 'Estonia', 372, 'Euro', '€', 'EUR', 'EST'),
('EG', 'Egypt', 20, 'Egyptian pound', '£ or ج.م', 'EGP', 'EGY'),
('EH', 'Western Sahara', 212, '', '', '', 'ESH'),
('ER', 'Eritrea', 291, 'Eritrean nakfa', 'Nfk', 'ERN', 'ERI'),
('ES', 'Spain', 34, 'Euro', '€', 'EUR', 'ESP'),
('ET', 'Ethiopia', 251, 'Ethiopian birr', 'Br', 'ETB', 'ETH'),
('FI', 'Finland', 358, 'Euro', '€', 'EUR', 'FIN'),
('FJ', 'Fiji Islands', 679, '', '', '', 'FJI'),
('FK', 'Falkland Islands', 500, 'Falkland Islands pou', '£', 'FKP', 'FLK'),
('FM', 'Micronesia', 691, 'Micronesian dollar', '$', '', 'FSM'),
('FO', 'Faroe Islands', 298, 'Danish krone', 'kr', 'DKK', 'FRO'),
('FR', 'France', 33, 'Euro', '€', 'EUR', 'FRA'),
('GA', 'Gabon', 241, 'Central African CFA ', 'Fr', 'XAF', 'GAB'),
('GB', 'United Kingdom', 44, 'British pound', '£', 'GBP', 'GBR'),
('GD', 'Grenada', 1473, 'East Caribbean dolla', '$', 'XCD', 'GRD'),
('GE', 'Georgia', 995, 'Georgian lari', 'ლ', 'GEL', 'GEO'),
('GF', 'French Guiana', 594, '', '', '', 'GUF'),
('GH', 'Ghana', 233, 'Ghana cedi', '₵', 'GHS', 'GHA'),
('GI', 'Gibraltar', 350, 'Gibraltar pound', '£', 'GIP', 'GIB'),
('GL', 'Greenland', 299, '', '', '', 'GRL'),
('GM', 'Gambia The', 220, '', '', '', 'GMB'),
('GN', 'Guinea', 224, 'Guinean franc', 'Fr', 'GNF', 'GIN'),
('GP', 'Guadeloupe', 590, '', '', '', 'GLP'),
('GQ', 'Equatorial Guinea', 240, 'Central African CFA ', 'Fr', 'XAF', 'GNQ'),
('GR', 'Greece', 30, 'Euro', '€', 'EUR', 'GRC'),
('GS', 'South Georgia', 0, '', '', '', 'SGS'),
('GT', 'Guatemala', 502, 'Guatemalan quetzal', 'Q', 'GTQ', 'GTM'),
('GU', 'Guam', 1671, '', '', '', 'GUM'),
('GW', 'Guinea-Bissau', 245, 'West African CFA fra', 'Fr', 'XOF', 'GNB'),
('GY', 'Guyana', 592, 'Guyanese dollar', '$', 'GYD', 'GUY'),
('HK', 'Hong Kong S.A.R.', 852, '', '', '', 'HKG'),
('HM', 'Heard and McDonald Islands', 0, '', '', '', 'HMD'),
('HN', 'Honduras', 504, 'Honduran lempira', 'L', 'HNL', 'HND'),
('HR', 'Croatia (Hrvatska)', 385, '', '', '', 'HRV'),
('HT', 'Haiti', 509, 'Haitian gourde', 'G', 'HTG', 'HTI'),
('HU', 'Hungary', 36, 'Hungarian forint', 'Ft', 'HUF', 'HUN'),
('ID', 'Indonesia', 62, 'Indonesian rupiah', 'Rp', 'IDR', 'IDN'),
('IE', 'Ireland', 353, 'Euro', '€', 'EUR', 'IRL'),
('IL', 'Israel', 972, 'Israeli new shekel', '₪', 'ILS', 'ISR'),
('IN', 'India', 91, 'Indian rupee', '₹', 'INR', 'IND'),
('IO', 'British Indian Ocean Territory', 246, 'United States dollar', '$', 'USD', 'IOT'),
('IQ', 'Iraq', 964, 'Iraqi dinar', 'ع.د', 'IQD', 'IRQ'),
('IR', 'Iran', 98, 'Iranian rial', '﷼', 'IRR', 'IRN'),
('IS', 'Iceland', 354, 'Icelandic króna', 'kr', 'ISK', 'ISL'),
('IT', 'Italy', 39, 'Euro', '€', 'EUR', 'ITA'),
('JM', 'Jamaica', 1876, 'Jamaican dollar', '$', 'JMD', 'JAM'),
('JO', 'Jordan', 962, 'Jordanian dinar', 'د.ا', 'JOD', 'JOR'),
('JP', 'Japan', 81, 'Japanese yen', '¥', 'JPY', 'JPN'),
('KE', 'Kenya', 254, 'Kenyan shilling', 'Sh', 'KES', 'KEN'),
('KG', 'Kyrgyzstan', 996, 'Kyrgyzstani som', 'лв', 'KGS', 'KGZ'),
('KH', 'Cambodia', 855, 'Cambodian riel', '៛', 'KHR', 'KHM'),
('KI', 'Kiribati', 686, 'Australian dollar', '$', 'AUD', 'KIR'),
('KM', 'Comoros', 269, 'Comorian franc', 'Fr', 'KMF', 'COM'),
('KN', 'Saint Kitts And Nevis', 1869, 'East Caribbean dolla', '$', 'XCD', 'KNA'),
('KP', 'Korea North', 850, '', '', '', 'PRK'),
('KR', 'Korea South', 82, '', '', '', 'KOR'),
('KW', 'Kuwait', 965, 'Kuwaiti dinar', 'د.ك', 'KWD', 'KWT'),
('KY', 'Cayman Islands', 1345, 'Cayman Islands dolla', '$', 'KYD', 'CYM'),
('KZ', 'Kazakhstan', 7, 'Kazakhstani tenge', '', 'KZT', 'KAZ'),
('LA', 'Laos', 856, 'Lao kip', '₭', 'LAK', 'LAO'),
('LB', 'Lebanon', 961, 'Lebanese pound', 'ل.ل', 'LBP', 'LBN'),
('LC', 'Saint Lucia', 1758, 'East Caribbean dolla', '$', 'XCD', 'LCA'),
('LI', 'Liechtenstein', 423, 'Swiss franc', 'Fr', 'CHF', 'LIE'),
('LK', 'Sri Lanka', 94, 'Sri Lankan rupee', 'Rs or රු', 'LKR', 'LKA'),
('LR', 'Liberia', 231, 'Liberian dollar', '$', 'LRD', 'LBR'),
('LS', 'Lesotho', 266, 'Lesotho loti', 'L', 'LSL', 'LSO'),
('LT', 'Lithuania', 370, 'Euro', '€', 'EUR', 'LTU'),
('LU', 'Luxembourg', 352, 'Euro', '€', 'EUR', 'LUX'),
('LV', 'Latvia', 371, 'Euro', '€', 'EUR', 'LVA'),
('LY', 'Libya', 218, 'Libyan dinar', 'ل.د', 'LYD', 'LBY'),
('MA', 'Morocco', 212, 'Moroccan dirham', 'د.م.', 'MAD', 'MAR'),
('MC', 'Monaco', 377, 'Euro', '€', 'EUR', 'MCO'),
('MD', 'Moldova', 373, 'Moldovan leu', 'L', 'MDL', 'MDA'),
('MG', 'Madagascar', 261, 'Malagasy ariary', 'Ar', 'MGA', 'MDG'),
('MH', 'Marshall Islands', 692, 'United States dollar', '$', 'USD', 'MHL'),
('MK', 'Macedonia', 389, '', '', '', 'MKD'),
('ML', 'Mali', 223, 'West African CFA fra', 'Fr', 'XOF', 'MLI'),
('MM', 'Myanmar', 95, 'Burmese kyat', 'Ks', 'MMK', 'MMR'),
('MN', 'Mongolia', 976, 'Mongolian tögrög', '₮', 'MNT', 'MNG'),
('MO', 'Macau S.A.R.', 853, '', '', '', 'MAC'),
('MP', 'Northern Mariana Islands', 1670, '', '', '', 'MNP'),
('MQ', 'Martinique', 596, '', '', '', 'MTQ'),
('MR', 'Mauritania', 222, 'Mauritanian ouguiya', 'UM', 'MRO', 'MRT'),
('MS', 'Montserrat', 1664, 'East Caribbean dolla', '$', 'XCD', 'MSR'),
('MT', 'Malta', 356, 'Euro', '€', 'EUR', 'MLT'),
('MU', 'Mauritius', 230, 'Mauritian rupee', '₨', 'MUR', 'MUS'),
('MV', 'Maldives', 960, 'Maldivian rufiyaa', '.ރ', 'MVR', 'MDV'),
('MW', 'Malawi', 265, 'Malawian kwacha', 'MK', 'MWK', 'MWI'),
('MX', 'Mexico', 52, 'Mexican peso', '$', 'MXN', 'MEX'),
('MY', 'Malaysia', 60, 'Malaysian ringgit', 'RM', 'MYR', 'MYS'),
('MZ', 'Mozambique', 258, 'Mozambican metical', 'MT', 'MZN', 'MOZ'),
('NA', 'Namibia', 264, 'Namibian dollar', '$', 'NAD', 'NAM'),
('NC', 'New Caledonia', 687, 'CFP franc', 'Fr', 'XPF', 'NCL'),
('NE', 'Niger', 227, 'West African CFA fra', 'Fr', 'XOF', 'NER'),
('NF', 'Norfolk Island', 672, '', '', '', 'NFK'),
('NG', 'Nigeria', 234, 'Nigerian naira', '₦', 'NGN', 'NGA'),
('NI', 'Nicaragua', 505, 'Nicaraguan córdoba', 'C$', 'NIO', 'NIC'),
('NL', 'Netherlands The', 31, '', '', '', 'NLD'),
('NO', 'Norway', 47, 'Norwegian krone', 'kr', 'NOK', 'NOR'),
('NP', 'Nepal', 977, 'Nepalese rupee', '₨', 'NPR', 'NPL'),
('NR', 'Nauru', 674, 'Australian dollar', '$', 'AUD', 'NRU'),
('NU', 'Niue', 683, 'New Zealand dollar', '$', 'NZD', 'NIU'),
('NZ', 'New Zealand', 64, 'New Zealand dollar', '$', 'NZD', 'NZL'),
('OM', 'Oman', 968, 'Omani rial', 'ر.ع.', 'OMR', 'OMN'),
('PA', 'Panama', 507, 'Panamanian balboa', 'B/.', 'PAB', 'PAN'),
('PE', 'Peru', 51, 'Peruvian nuevo sol', 'S/.', 'PEN', 'PER'),
('PF', 'French Polynesia', 689, 'CFP franc', 'Fr', 'XPF', 'PYF'),
('PG', 'Papua new Guinea', 675, 'Papua New Guinean ki', 'K', 'PGK', 'PNG'),
('PH', 'Philippines', 63, 'Philippine peso', '₱', 'PHP', 'PHL'),
('PK', 'Pakistan', 92, 'Pakistani rupee', '₨', 'PKR', 'PAK'),
('PL', 'Poland', 48, 'Polish złoty', 'zł', 'PLN', 'POL'),
('PM', 'Saint Pierre and Miquelon', 508, '', '', '', 'SPM'),
('PN', 'Pitcairn Island', 0, '', '', '', 'PCN'),
('PR', 'Puerto Rico', 1787, '', '', '', 'PRI'),
('PS', 'Palestinian Territory Occupied', 970, '', '', '', 'PSE'),
('PT', 'Portugal', 351, 'Euro', '€', 'EUR', 'PRT'),
('PW', 'Palau', 680, 'Palauan dollar', '$', '', 'PLW'),
('PY', 'Paraguay', 595, 'Paraguayan guaraní', '₲', 'PYG', 'PRY'),
('QA', 'Qatar', 974, 'Qatari riyal', 'ر.ق', 'QAR', 'QAT'),
('RE', 'Reunion', 262, '', '', '', 'REU'),
('RO', 'Romania', 40, 'Romanian leu', 'lei', 'RON', 'ROU'),
('RS', 'Serbia', 381, 'Serbian dinar', 'дин. or din.', 'RSD', 'SRB'),
('RU', 'Russia', 70, 'Russian ruble', '', 'RUB', 'RUS'),
('RW', 'Rwanda', 250, 'Rwandan franc', 'Fr', 'RWF', 'RWA'),
('SA', 'Saudi Arabia', 966, 'Saudi riyal', 'ر.س', 'SAR', 'SAU'),
('SB', 'Solomon Islands', 677, 'Solomon Islands doll', '$', 'SBD', 'SLB'),
('SC', 'Seychelles', 248, 'Seychellois rupee', '₨', 'SCR', 'SYC'),
('SD', 'Sudan', 249, 'Sudanese pound', 'ج.س.', 'SDG', 'SDN'),
('SE', 'Sweden', 46, 'Swedish krona', 'kr', 'SEK', 'SWE'),
('SG', 'Singapore', 65, 'Brunei dollar', '$', 'BND', 'SGP'),
('SH', 'Saint Helena', 290, 'Saint Helena pound', '£', 'SHP', 'SHN'),
('SI', 'Slovenia', 386, 'Euro', '€', 'EUR', 'SVN'),
('SJ', 'Svalbard And Jan Mayen Islands', 47, '', '', '', 'SJM'),
('SK', 'Slovakia', 421, 'Euro', '€', 'EUR', 'SVK'),
('SL', 'Sierra Leone', 232, 'Sierra Leonean leone', 'Le', 'SLL', 'SLE'),
('SM', 'San Marino', 378, 'Euro', '€', 'EUR', 'SMR'),
('SN', 'Senegal', 221, 'West African CFA fra', 'Fr', 'XOF', 'SEN'),
('SO', 'Somalia', 252, 'Somali shilling', 'Sh', 'SOS', 'SOM'),
('SR', 'Suriname', 597, 'Surinamese dollar', '$', 'SRD', 'SUR'),
('SS', 'South Sudan', 211, 'South Sudanese pound', '£', 'SSP', 'SSD'),
('ST', 'Sao Tome and Principe', 239, 'São Tomé and Príncip', 'Db', 'STD', 'STP'),
('SV', 'El Salvador', 503, 'United States dollar', '$', 'USD', 'SLV'),
('SY', 'Syria', 963, 'Syrian pound', '£ or ل.س', 'SYP', 'SYR'),
('SZ', 'Swaziland', 268, 'Swazi lilangeni', 'L', 'SZL', 'SWZ'),
('TC', 'Turks And Caicos Islands', 1649, 'United States dollar', '$', 'USD', 'TCA'),
('TD', 'Chad', 235, 'Central African CFA ', 'Fr', 'XAF', 'TCD'),
('TF', 'French Southern Territories', 0, '', '', '', 'ATF'),
('TG', 'Togo', 228, 'West African CFA fra', 'Fr', 'XOF', 'TGO'),
('TH', 'Thailand', 66, 'Thai baht', '฿', 'THB', 'THA'),
('TJ', 'Tajikistan', 992, 'Tajikistani somoni', 'ЅМ', 'TJS', 'TJK'),
('TK', 'Tokelau', 690, '', '', '', 'TKL'),
('TM', 'Turkmenistan', 7370, 'Turkmenistan manat', 'm', 'TMT', 'TKM'),
('TN', 'Tunisia', 216, 'Tunisian dinar', 'د.ت', 'TND', 'TUN'),
('TO', 'Tonga', 676, 'Tongan paʻanga', 'T$', 'TOP', 'TON'),
('TP', 'East Timor', 670, 'United States dollar', '$', 'USD'),
('TR', 'Turkey', 90, 'Turkish lira', '', 'TRY', 'TUR'),
('TT', 'Trinidad And Tobago', 1868, 'Trinidad and Tobago ', '$', 'TTD', 'TTO'),
('TV', 'Tuvalu', 688, 'Australian dollar', '$', 'AUD', 'TUV'),
('TW', 'Taiwan', 886, 'New Taiwan dollar', '$', 'TWD', 'TWN'),
('TZ', 'Tanzania', 255, 'Tanzanian shilling', 'Sh', 'TZS', 'TZA'),
('UA', 'Ukraine', 380, 'Ukrainian hryvnia', '₴', 'UAH', 'UKR'),
('UG', 'Uganda', 256, 'Ugandan shilling', 'Sh', 'UGX', 'UGA'),
('UM', 'United States Minor Outlying Islands', 1, '', '', '', 'UMI'),
('US', 'United States', 1, 'United States dollar', '$', 'USD', 'USA'),
('UY', 'Uruguay', 598, 'Uruguayan peso', '$', 'UYU', 'URY'),
('UZ', 'Uzbekistan', 998, 'Uzbekistani som', '', 'UZS', 'UZB'),
('VA', 'Vatican City State (Holy See)', 39, '', '', '', 'VAT'),
('VC', 'Saint Vincent And The Grenadines', 1784, 'East Caribbean dolla', '$', 'XCD', 'VCT'),
('VE', 'Venezuela', 58, 'Venezuelan bolívar', 'Bs F', 'VEF', 'VEN'),
('VG', 'Virgin Islands (British)', 1284, '', '', '', 'VGB'),
('VI', 'Virgin Islands (US)', 1340, '', '', '', 'VIR'),
('VN', 'Vietnam', 84, 'Vietnamese đồng', '₫', 'VND', 'VNM'),
('VU', 'Vanuatu', 678, 'Vanuatu vatu', 'Vt', 'VUV', 'VUT'),
('WF', 'Wallis And Futuna Islands', 681, '', '', '', 'WLF'),
('WS', 'Samoa', 684, 'Samoan tālā', 'T', 'WST', 'WSM'),
('XA', 'External Territories of Australia', 61, '', '', ''),
('XG', 'Smaller Territories of the UK', 44, '', '', ''),
('XJ', 'Jersey', 44, 'British pound', '£', 'GBP'),
('XM', 'Man (Isle of)', 44, '', '', ''),
('XU', 'Guernsey and Alderney', 44, '', '', ''),
('YE', 'Yemen', 967, 'Yemeni rial', '﷼', 'YER', 'YEM'),
('YT', 'Mayotte', 269, '', '', '', 'MYT'),
('YU', 'Yugoslavia', 38, '', '', ''),
('ZA', 'South Africa', 27, 'South African rand', 'R', 'ZAR', 'ZAF'),
('ZM', 'Zambia', 260, 'Zambian kwacha', 'ZK', 'ZMW', 'ZMB'),
('ZW', 'Zimbabwe', 263, 'Botswana pula', 'P', 'BWP', 'ZWE');
