--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/11/2019 7:37:56 PM
-- Server version: 5.7.10-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO shopbook.categories(CAT_CODE, CAT_NAME, NOTES, LAST_MODIFIED, CAT_IMG_NAME, CAT_IMG_TYPE) VALUES
('C0000', 'Reserved', 'n/a', '2019-06-10 14:14:28', 'D:\\shopbook\\Categories\\190610_141418.jpeg', '.jpeg');