package com.shopbook.sysadmin.model.view;

import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 04 20:28:10 EET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReferencesVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ReferencesVImpl() {
    }
    public void afterCommit(TransactionEvent transactionEvent) {
        executeQuery();
        super.afterCommit(transactionEvent);
    }

}

