package com.shopbook.home.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 27 12:52:22 EET 2021
// ---------------------------------------------------------------------
public interface HmSkuV extends ViewObject {
    void setClrSizeForDetailSkuAccessorViewObject(String _clrCode, String _szCode);
}

