package com.shopbook.shopadmin.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 28 22:20:39 EET 2021
// ---------------------------------------------------------------------
public interface ShBkShopAdmin extends ApplicationModule {
    void insMissedSkuSizes(String vSkuClrCode, int vQntyInStock, float vLastPrice, float vOldPrice);

    void upldSkuClrImg(String imgName, String imgPath, String imgType, String imgSeq, String imgCode, String skuClrCode,
                       String skuClrImgCode);
}

