package com.shopbook.shopadmin.model.am;

import com.shopbook.shopadmin.model.am.common.ShBkShopAdmin;

import java.sql.CallableStatement;

import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 28 22:19:28 EET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShBkShopAdminImpl extends ApplicationModuleImpl implements ShBkShopAdmin {
    /**
     * This is the default constructor (do not remove).
     */
    public ShBkShopAdminImpl() {
    }
    /**Method to set Sku Color Image data
        */
        public void upldSkuClrImg(String imgName, String imgPath,String imgType,
        String imgSeq, String imgCode, String skuClrCode, String skuClrImgCode) {
        ViewObject fileVo = this.getCrudSkuClrImagesV();
        Row newRow = fileVo.createRow();
            newRow.setAttribute("ImgCode", imgCode);
            newRow.setAttribute("ImgName", imgName);
            newRow.setAttribute("ImgPath", imgPath);
            newRow.setAttribute("ImgType", imgType);
            newRow.setAttribute("SkuClrCode", skuClrCode);
            newRow.setAttribute("SkuClrImgCode", skuClrImgCode);
        fileVo.insertRow(newRow);
        this.getDBTransaction().commit();
        fileVo.executeQuery();
        }

    public void insMissedSkuSizes(String vSkuClrCode, int vQntyInStock, float vLastPrice, float vOldPrice) {
        DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
        CallableStatement statement = dbti.createCallableStatement(("call insertMissedSkuSizes(?,?,?,?);"), 0);
        try {
    //            System.out.println(vSkuClrCode);
            statement.setString(1,vSkuClrCode);
            statement.setInt(2, vQntyInStock);
            statement.setFloat(3, vLastPrice);
            statement.setFloat(4, vOldPrice);
            statement.execute();
    //         System.out.println("Done.");
        } catch (SQLException sqlerr) {
            throw new JboException(sqlerr);
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
            } catch (SQLException closeerr) {
                throw new JboException(closeerr);
            }
        }
    }
    /**
     * Container's getter for ShopSubCatsV.
     * @return ShopSubCatsV
     */
    public ViewObjectImpl getShopSubCatsV() {
        return (ViewObjectImpl) findViewObject("ShopSubCatsV");
    }

    /**
     * Container's getter for ShopSubCatPropClassesV.
     * @return ShopSubCatPropClassesV
     */
    public ViewObjectImpl getShopSubCatPropClassesV() {
        return (ViewObjectImpl) findViewObject("ShopSubCatPropClassesV");
    }

    /**
     * Container's getter for ShopSubCatPropClassDetsV.
     * @return ShopSubCatPropClassDetsV
     */
    public ViewObjectImpl getShopSubCatPropClassDetsV() {
        return (ViewObjectImpl) findViewObject("ShopSubCatPropClassDetsV");
    }

    /**
     * Container's getter for CrudShopSubCatPropClassesV1.
     * @return CrudShopSubCatPropClassesV1
     */
    public ViewObjectImpl getCrudShopSubCatPropClassesV1() {
        return (ViewObjectImpl) findViewObject("CrudShopSubCatPropClassesV1");
    }

    /**
     * Container's getter for CrudShopSubCatPropClassDetsV1.
     * @return CrudShopSubCatPropClassDetsV1
     */
    public ViewObjectImpl getCrudShopSubCatPropClassDetsV1() {
        return (ViewObjectImpl) findViewObject("CrudShopSubCatPropClassDetsV1");
    }

    /**
     * Container's getter for ShopsV.
     * @return ShopsV
     */
    public ViewObjectImpl getShopsV() {
        return (ViewObjectImpl) findViewObject("ShopsV");
    }

    /**
     * Container's getter for ShopsBranchesV.
     * @return ShopsBranchesV
     */
    public ViewObjectImpl getShopsBranchesV() {
        return (ViewObjectImpl) findViewObject("ShopsBranchesV");
    }

    /**
     * Container's getter for ShopsTreeV.
     * @return ShopsTreeV
     */
    public ViewObjectImpl getShopsTreeV() {
        return (ViewObjectImpl) findViewObject("ShopsTreeV");
    }

    /**
     * Container's getter for ShopsTreeChildV.
     * @return ShopsTreeChildV
     */
    public ViewObjectImpl getShopsTreeChildV() {
        return (ViewObjectImpl) findViewObject("ShopsTreeChildV");
    }

    /**
     * Container's getter for SysParametersV.
     * @return SysParametersV
     */
    public ViewObjectImpl getSysParametersV() {
        return (ViewObjectImpl) findViewObject("SysParametersV");
    }

    /**
     * Container's getter for SpShopSubCatsV.
     * @return SpShopSubCatsV
     */
    public ViewObjectImpl getSpShopSubCatsV() {
        return (ViewObjectImpl) findViewObject("SpShopSubCatsV");
    }

    /**
     * Container's getter for SpSkusV.
     * @return SpSkusV
     */
    public ViewObjectImpl getSpSkusV() {
        return (ViewObjectImpl) findViewObject("SpSkusV");
    }

    /**
     * Container's getter for SpSkuSizesV.
     * @return SpSkuSizesV
     */
    public ViewObjectImpl getSpSkuSizesV() {
        return (ViewObjectImpl) findViewObject("SpSkuSizesV");
    }

    /**
     * Container's getter for SpSkuColorsV.
     * @return SpSkuColorsV
     */
    public ViewObjectImpl getSpSkuColorsV() {
        return (ViewObjectImpl) findViewObject("SpSkuColorsV");
    }

    /**
     * Container's getter for SpSkuPropDetsV.
     * @return SpSkuPropDetsV
     */
    public ViewObjectImpl getSpSkuPropDetsV() {
        return (ViewObjectImpl) findViewObject("SpSkuPropDetsV");
    }

    /**
     * Container's getter for SpSkuUnitsV.
     * @return SpSkuUnitsV
     */
    public ViewObjectImpl getSpSkuUnitsV() {
        return (ViewObjectImpl) findViewObject("SpSkuUnitsV");
    }

    /**
     * Container's getter for CrudSkusV.
     * @return CrudSkusV
     */
    public ViewObjectImpl getCrudSkusV() {
        return (ViewObjectImpl) findViewObject("CrudSkusV");
    }

    /**
     * Container's getter for CrudSkuColorsV.
     * @return CrudSkuColorsV
     */
    public ViewObjectImpl getCrudSkuColorsV() {
        return (ViewObjectImpl) findViewObject("CrudSkuColorsV");
    }

    /**
     * Container's getter for CrudSkuClrImagesV.
     * @return CrudSkuClrImagesV
     */
    public ViewObjectImpl getCrudSkuClrImagesV() {
        return (ViewObjectImpl) findViewObject("CrudSkuClrImagesV");
    }

    /**
     * Container's getter for SkuSizeColorsV.
     * @return SkuSizeColorsV
     */
    public ViewObjectImpl getSkuSizeColorsV() {
        return (ViewObjectImpl) findViewObject("SkuSizeColorsV");
    }

    /**
     * Container's getter for SkuPropDetsV.
     * @return SkuPropDetsV
     */
    public ViewObjectImpl getSkuPropDetsV() {
        return (ViewObjectImpl) findViewObject("SkuPropDetsV");
    }

    /**
     * Container's getter for SkuAssemblyCompsV.
     * @return SkuAssemblyCompsV
     */
    public ViewObjectImpl getSkuAssemblyCompsV() {
        return (ViewObjectImpl) findViewObject("SkuAssemblyCompsV");
    }

    /**
     * Container's getter for SkuCompAssembliesV.
     * @return SkuCompAssembliesV
     */
    public ViewObjectImpl getSkuCompAssembliesV() {
        return (ViewObjectImpl) findViewObject("SkuCompAssembliesV");
    }

    /**
     * Container's getter for CreateAsAssemblyV.
     * @return CreateAsAssemblyV
     */
    public ViewObjectImpl getCreateAsAssemblyV() {
        return (ViewObjectImpl) findViewObject("CreateAsAssemblyV");
    }

    /**
     * Container's getter for SkuAddToAssembliesV.
     * @return SkuAddToAssembliesV
     */
    public ViewObjectImpl getSkuAddToAssembliesV() {
        return (ViewObjectImpl) findViewObject("SkuAddToAssembliesV");
    }

    /**
     * Container's getter for SkusSetV.
     * @return SkusSetV
     */
    public ViewObjectImpl getSkusSetV() {
        return (ViewObjectImpl) findViewObject("SkusSetV");
    }

    /**
     * Container's getter for SkuSetCompsV.
     * @return SkuSetCompsV
     */
    public ViewObjectImpl getSkuSetCompsV() {
        return (ViewObjectImpl) findViewObject("SkuSetCompsV");
    }


    /**
     * Container's getter for SkuUnitsV.
     * @return SkuUnitsV
     */
    public ViewObjectImpl getSkuUnitsV() {
        return (ViewObjectImpl) findViewObject("SkuUnitsV");
    }

    /**
     * Container's getter for ShopCategoryAdminsV.
     * @return ShopCategoryAdminsV
     */
    public ViewObjectImpl getShopCategoryAdminsV() {
        return (ViewObjectImpl) findViewObject("ShopCategoryAdminsV");
    }

    /**
     * Container's getter for CrudShopCategoryAdminsV.
     * @return CrudShopCategoryAdminsV
     */
    public ViewObjectImpl getCrudShopCategoryAdminsV() {
        return (ViewObjectImpl) findViewObject("CrudShopCategoryAdminsV");
    }

    /**
     * Container's getter for AdminsV.
     * @return AdminsV
     */
    public ViewObjectImpl getAdminsV() {
        return (ViewObjectImpl) findViewObject("AdminsV");
    }

    /**
     * Container's getter for ShopCategoryAdminsV1.
     * @return ShopCategoryAdminsV1
     */
    public ViewObjectImpl getShopCategoryAdminsV1() {
        return (ViewObjectImpl) findViewObject("ShopCategoryAdminsV1");
    }

    /**
     * Container's getter for GeneralTermsV.
     * @return GeneralTermsV
     */
    public ViewObjectImpl getGeneralTermsV() {
        return (ViewObjectImpl) findViewObject("GeneralTermsV");
    }

    /**
     * Container's getter for RtrnTermsV.
     * @return RtrnTermsV
     */
    public ViewObjectImpl getRtrnTermsV() {
        return (ViewObjectImpl) findViewObject("RtrnTermsV");
    }

    /**
     * Container's getter for ShippingTermsV.
     * @return ShippingTermsV
     */
    public ViewObjectImpl getShippingTermsV() {
        return (ViewObjectImpl) findViewObject("ShippingTermsV");
    }

    /**
     * Container's getter for CrudGeneralTermsV.
     * @return CrudGeneralTermsV
     */
    public ViewObjectImpl getCrudGeneralTermsV() {
        return (ViewObjectImpl) findViewObject("CrudGeneralTermsV");
    }

    /**
     * Container's getter for CrudRtrnTermsV.
     * @return CrudRtrnTermsV
     */
    public ViewObjectImpl getCrudRtrnTermsV() {
        return (ViewObjectImpl) findViewObject("CrudRtrnTermsV");
    }

    /**
     * Container's getter for CrudShippingTermsV.
     * @return CrudShippingTermsV
     */
    public ViewObjectImpl getCrudShippingTermsV() {
        return (ViewObjectImpl) findViewObject("CrudShippingTermsV");
    }

    /**
     * Container's getter for ShoppingMasterV.
     * @return ShoppingMasterV
     */
    public ViewObjectImpl getShoppingMasterV() {
        return (ViewObjectImpl) findViewObject("ShoppingMasterV");
    }

    /**
     * Container's getter for ShoppingDetV.
     * @return ShoppingDetV
     */
    public ViewObjectImpl getShoppingDetV() {
        return (ViewObjectImpl) findViewObject("ShoppingDetV");
    }

    /**
     * Container's getter for SysImagesView.
     * @return SysImagesView
     */
    public ViewObjectImpl getSysImagesView() {
        return (ViewObjectImpl) findViewObject("SysImagesView");
    }

    /**
     * Container's getter for ShopCatPropClassVL1.
     * @return ShopCatPropClassVL1
     */
    public ViewLinkImpl getShopCatPropClassVL1() {
        return (ViewLinkImpl) findViewLink("ShopCatPropClassVL1");
    }

    /**
     * Container's getter for PropClssToDetVL1.
     * @return PropClssToDetVL1
     */
    public ViewLinkImpl getPropClssToDetVL1() {
        return (ViewLinkImpl) findViewLink("PropClssToDetVL1");
    }

    /**
     * Container's getter for ShopCatPropClassVL2.
     * @return ShopCatPropClassVL2
     */
    public ViewLinkImpl getShopCatPropClassVL2() {
        return (ViewLinkImpl) findViewLink("ShopCatPropClassVL2");
    }

    /**
     * Container's getter for PropClssToDetVL2.
     * @return PropClssToDetVL2
     */
    public ViewLinkImpl getPropClssToDetVL2() {
        return (ViewLinkImpl) findViewLink("PropClssToDetVL2");
    }

    /**
     * Container's getter for ShopTreeVLink1.
     * @return ShopTreeVLink1
     */
    public ViewLinkImpl getShopTreeVLink1() {
        return (ViewLinkImpl) findViewLink("ShopTreeVLink1");
    }

    /**
     * Container's getter for ShopcatSkuVL1.
     * @return ShopcatSkuVL1
     */
    public ViewLinkImpl getShopcatSkuVL1() {
        return (ViewLinkImpl) findViewLink("ShopcatSkuVL1");
    }

    /**
     * Container's getter for SkuToSkuSizesVL1.
     * @return SkuToSkuSizesVL1
     */
    public ViewLinkImpl getSkuToSkuSizesVL1() {
        return (ViewLinkImpl) findViewLink("SkuToSkuSizesVL1");
    }

    /**
     * Container's getter for SkuToColorsVL1.
     * @return SkuToColorsVL1
     */
    public ViewLinkImpl getSkuToColorsVL1() {
        return (ViewLinkImpl) findViewLink("SkuToColorsVL1");
    }

    /**
     * Container's getter for SkuToSkuPropVL1.
     * @return SkuToSkuPropVL1
     */
    public ViewLinkImpl getSkuToSkuPropVL1() {
        return (ViewLinkImpl) findViewLink("SkuToSkuPropVL1");
    }

    /**
     * Container's getter for SkuToSkuUnitVL3.
     * @return SkuToSkuUnitVL3
     */
    public ViewLinkImpl getSkuToSkuUnitVL3() {
        return (ViewLinkImpl) findViewLink("SkuToSkuUnitVL3");
    }

    /**
     * Container's getter for SkuToColorsVL2.
     * @return SkuToColorsVL2
     */
    public ViewLinkImpl getSkuToColorsVL2() {
        return (ViewLinkImpl) findViewLink("SkuToColorsVL2");
    }

    /**
     * Container's getter for SkuClrToSkuClrImgVL1.
     * @return SkuClrToSkuClrImgVL1
     */
    public ViewLinkImpl getSkuClrToSkuClrImgVL1() {
        return (ViewLinkImpl) findViewLink("SkuClrToSkuClrImgVL1");
    }

    /**
     * Container's getter for SkuClrToSkuSzClrVL1.
     * @return SkuClrToSkuSzClrVL1
     */
    public ViewLinkImpl getSkuClrToSkuSzClrVL1() {
        return (ViewLinkImpl) findViewLink("SkuClrToSkuSzClrVL1");
    }

    /**
     * Container's getter for SkuToSkuPropVL2.
     * @return SkuToSkuPropVL2
     */
    public ViewLinkImpl getSkuToSkuPropVL2() {
        return (ViewLinkImpl) findViewLink("SkuToSkuPropVL2");
    }

    /**
     * Container's getter for MainSkuToAssemblyVL.
     * @return MainSkuToAssemblyVL
     */
    public ViewLinkImpl getMainSkuToAssemblyVL() {
        return (ViewLinkImpl) findViewLink("MainSkuToAssemblyVL");
    }

    /**
     * Container's getter for SkuToAssCompVL.
     * @return SkuToAssCompVL
     */
    public ViewLinkImpl getSkuToAssCompVL() {
        return (ViewLinkImpl) findViewLink("SkuToAssCompVL");
    }

    /**
     * Container's getter for MainSkuToAssemblyVL1.
     * @return MainSkuToAssemblyVL1
     */
    public ViewLinkImpl getMainSkuToAssemblyVL1() {
        return (ViewLinkImpl) findViewLink("MainSkuToAssemblyVL1");
    }


    /**
     * Container's getter for SkuToSkuUnitVL1.
     * @return SkuToSkuUnitVL1
     */
    public ViewLinkImpl getSkuToSkuUnitVL1() {
        return (ViewLinkImpl) findViewLink("SkuToSkuUnitVL1");
    }

    /**
     * Container's getter for ShopCatsToAdminCatVL1.
     * @return ShopCatsToAdminCatVL1
     */
    public ViewLinkImpl getShopCatsToAdminCatVL1() {
        return (ViewLinkImpl) findViewLink("ShopCatsToAdminCatVL1");
    }

    /**
     * Container's getter for ShopCatsToAdminCatVL2.
     * @return ShopCatsToAdminCatVL2
     */
    public ViewLinkImpl getShopCatsToAdminCatVL2() {
        return (ViewLinkImpl) findViewLink("ShopCatsToAdminCatVL2");
    }

    /**
     * Container's getter for AdminToAdminCatVL1.
     * @return AdminToAdminCatVL1
     */
    public ViewLinkImpl getAdminToAdminCatVL1() {
        return (ViewLinkImpl) findViewLink("AdminToAdminCatVL1");
    }

    /**
     * Container's getter for ShoppingMastDetVL1.
     * @return ShoppingMastDetVL1
     */
    public ViewLinkImpl getShoppingMastDetVL1() {
        return (ViewLinkImpl) findViewLink("ShoppingMastDetVL1");
    }

    /**
     * Container's getter for CountriesV1.
     * @return CountriesV1
     */
    public ViewObjectImpl getCountriesV() {
        return (ViewObjectImpl) findViewObject("CountriesV");
    }


    /**
     * Container's getter for Offers1.
     * @return Offers1
     */
    public ViewObjectImpl getCrudOffersV() {
        return (ViewObjectImpl) findViewObject("CrudOffersV");
    }

    /**
     * Container's getter for OfferDets1.
     * @return OfferDets1
     */
    public ViewObjectImpl getCrudOfferDetsV() {
        return (ViewObjectImpl) findViewObject("CrudOfferDetsV");
    }

    /**
     * Container's getter for OffersToOfferDetVL2.
     * @return OffersToOfferDetVL2
     */
    public ViewLinkImpl getOffersToOfferDetVL2() {
        return (ViewLinkImpl) findViewLink("OffersToOfferDetVL2");
    }

    /**
     * Container's getter for OfferDetsDets1.
     * @return OfferDetsDets1
     */
    public ViewObjectImpl getCrudOfferDetsDetsV() {
        return (ViewObjectImpl) findViewObject("CrudOfferDetsDetsV");
    }

    /**
     * Container's getter for FkOfferDetsDetsDetsVL2.
     * @return FkOfferDetsDetsDetsVL2
     */
    public ViewLinkImpl getFkOfferDetsDetsDetsVL2() {
        return (ViewLinkImpl) findViewLink("FkOfferDetsDetsDetsVL2");
    }

    /**
     * Container's getter for SkuColorLOV1.
     * @return SkuColorLOV1
     */
    public ViewObjectImpl getSkuColorLOV1() {
        return (ViewObjectImpl) findViewObject("SkuColorLOV1");
    }

    /**
     * Container's getter for SkuClrSizesLOV1.
     * @return SkuClrSizesLOV1
     */
    public ViewObjectImpl getSkuClrSizesLOV1() {
        return (ViewObjectImpl) findViewObject("SkuClrSizesLOV1");
    }

    /**
     * Container's getter for SkuLOV1.
     * @return SkuLOV1
     */
    public ViewObjectImpl getSkuLOV1() {
        return (ViewObjectImpl) findViewObject("SkuLOV1");
    }

    /**
     * Container's getter for Offers1.
     * @return Offers1
     */
    public ViewObjectImpl getOffersV() {
        return (ViewObjectImpl) findViewObject("OffersV");
    }

    /**
     * Container's getter for OfferDets1.
     * @return OfferDets1
     */
    public ViewObjectImpl getOfferDets() {
        return (ViewObjectImpl) findViewObject("OfferDets");
    }

    /**
     * Container's getter for OffersToOfferDetVL1.
     * @return OffersToOfferDetVL1
     */
    public ViewLinkImpl getOffersToOfferDetVL1() {
        return (ViewLinkImpl) findViewLink("OffersToOfferDetVL1");
    }

    /**
     * Container's getter for ShopsV1.
     * @return ShopsV1
     */
    public ViewObjectImpl getParentShopDataInEmailV() {
        return (ViewObjectImpl) findViewObject("ParentShopDataInEmailV");
    }
}

